/* Auto-generated by tools/bump_version.py - do not edit manually */
#ifndef ESPHELPER_VERSION_H
#define ESPHELPER_VERSION_H

#define ESPHELPER_VERSION_MAJOR 0
#define ESPHELPER_VERSION_MINOR 1
#define ESPHELPER_VERSION_PATCH 1
#define ESPHELPER_VERSION_STR "0.1.1"

#endif // ESPHELPER_VERSION_H
