/* Auto-generated by tools/bump_version.py - do not edit manually */
#ifndef ESPHELPER_VERSION_H
#define ESPHELPER_VERSION_H

#define ESPHELPER_VERSION_MAJOR 1
#define ESPHELPER_VERSION_MINOR 0
#define ESPHELPER_VERSION_PATCH 2
#define ESPHELPER_VERSION_STR "1.0.2"

#endif // ESPHELPER_VERSION_H
